sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t rkbell/docker-react1 -f Dockerfile.dev .

script:
  - docker run -e CI=true rkbell/docker-react1 npm run test